# KNN

In [22]:
import pandas as pd
dataset_url = "https://raw.githubusercontent.com/CAHYANIR/data/main/dataR2.csv"
df = pd.read_csv(dataset_url)
df.head()

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  Classification  
0  417.114               1  
1  468.786               1  
2  554.697               1  
3  928.220               1  
4  773.920               1

In [4]:
df.shape

(116, 10)

In [5]:
X = df.drop(columns=['Classification'])
X.head()

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  
0  417.114  
1  468.786  
2  554.697  
3  928.220  
4  773.920

In [8]:
y = df['Classification'].values
y[0:5]

array([1, 1, 1, 1, 1])

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [11]:
knn.predict(X_test)[0:29]

array([1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2,
       2, 2])

In [12]:
knn.score(X_test, y_test)

0.3333333333333333

In [13]:
from sklearn.model_selection import cross_val_score
import numpy as np
knn_cv = KNeighborsClassifier(n_neighbors=3)
cv_scores = cross_val_score(knn_cv, X, y, cv=5)
print(cv_scores)
print('cv_scores mean:{}'.format(np.mean(cv_scores)))

[0.5        0.52173913 0.47826087 0.47826087 0.60869565]
cv_scores mean:0.5173913043478261


In [14]:
from sklearn.model_selection import GridSearchCV
knn2 = KNeighborsClassifier()
param_grid = {'n_neighbors': np.arange(1, 25)}
knn_gscv = GridSearchCV(knn2, param_grid, cv=5)
knn_gscv.fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])})

In [15]:
knn_gscv.best_params_

{'n_neighbors': 23}

In [16]:
knn_gscv.best_score_

0.5688405797101449

#DECISION TREE

In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.tree import DecisionTreeClassifier      
from sklearn.model_selection import train_test_split 
from sklearn import metrics                         
from sklearn.metrics import classification_report 

In [26]:
dataset_url = "https://raw.githubusercontent.com/CAHYANIR/data/main/dataR2.csv"
df = pd.read_csv(dataset_url)
df.head()

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  Classification  
0  417.114               1  
1  468.786               1  
2  554.697               1  
3  928.220               1  
4  773.920               1

In [27]:
df = df.drop(labels='Age', axis=1)
df = df.drop(labels='Classification', axis=1)

In [28]:
df.head()

BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  
0  417.114  
1  468.786  
2  554.697  
3  928.220  
4  773.920

In [29]:
df.corr()

BMI   Glucose   Insulin      HOMA    Leptin  Adiponectin  \
BMI          1.000000  0.138845  0.145295  0.114480  0.569593    -0.302735   
Glucose      0.138845  1.000000  0.504653  0.696212  0.305080    -0.122121   
Insulin      0.145295  0.504653  1.000000  0.932198  0.301462    -0.031296   
HOMA         0.114480  0.696212  0.932198  1.000000  0.327210    -0.056337   
Leptin       0.569593  0.305080  0.301462  0.327210  1.000000    -0.095389   
Adiponectin -0.302735 -0.122121 -0.031296 -0.056337 -0.095389     1.000000   
Resistin     0.195350  0.291327  0.146731  0.231101  0.256234    -0.252363   
MCP.1        0.224038  0.264879  0.174356  0.259529  0.014009    -0.200694   

             Resistin     MCP.1  
BMI          0.195350  0.224038  
Glucose      0.291327  0.264879  
Insulin      0.146731  0.174356  
HOMA         0.231101  0.259529  
Leptin       0.256234  0.014009  
Adiponectin -0.252363 -0.200694  
Resistin     1.000000  0.366474  
MCP.1        0.366474  1.000000

In [41]:
X = df.iloc[:,0:4].values 
Y = df.iloc[:, 4].values  
print(X.shape, '\n')
print(Y.shape)

(116, 4) 

(116,)


In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [44]:
# Model dengan hyperparameter default
model_default = DecisionTreeClassifier()
model_default = model_default.fit(X_train, y_train)

# Model dengan tuning hyperparameter
model_DT = DecisionTreeClassifier(criterion='entropy', max_depth=None, max_leaf_nodes=None,  random_state=None)
model_DT = model_DT.fit(X_train, y_train)

ValueError: ignored

In [45]:
# hasil prediksi training set
y_pred_train = model_DT.predict(X_train)

# hasil prediksi test set
y_pred = model_DT.predict(X_test)

# Train set score
print("Train Accuracy   :", metrics.accuracy_score(y_train, y_pred_train))
print("Train Precission :", metrics.precision_score(y_train, y_pred_train))
print("Train Recall     :", metrics.recall_score(y_train, y_pred_train), '\n')

# Test set score
print("Test Accuracy   :", metrics.accuracy_score(y_test, y_pred))
print("Test Precission :", metrics.precision_score(y_test, y_pred))
print("Test Recall     :", metrics.recall_score(y_test, y_pred))

NameError: ignored